# install.R
install.pacakges("rlang")
install.packages("ggplot2")
install.packages("dplyr", dependencies = TRUE)
install.packages("forcats")
install.packages("hrbrthemes")
install.packages("viridis")
install.packages("zoo")
install.packages("corrplot")
install.packages("maps")
